#!/bin/bash

# Get the current Kitty window ID
KITTY_WINDOW_ID=$(kitty @ ls | jq -r '.[] | select(.is_focused).id')

if [[ "$1" == "active" ]]; then
  # Set border to purple when TMUX is active
  kitty @ set-window-border --match id:$KITTY_WINDOW_ID '#c678dd'
elif [[ "$1" == "inactive" ]]; then
  # Reset border when TMUX is inactive
  kitty @ set-window-border --match id:$KITTY_WINDOW_ID none
fi
