#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"

### AUTO PADDING (from fyabai) ###
# yabai -m config auto_padding on
# yabai -m config auto_padding_min_aspect 3.5
# yabai -m config auto_padding_width 1600
# yabai -m config auto_padding_height 1380

yabai -m config external_bar all:35:0 \
	mouse_follows_focus on \
	focus_follows_mouse off \
	window_zoom_persist off \
	window_placement second_child \
	window_shadow float \
	window_opacity on \
	window_opacity_duration 0.2 \
	active_window_opacity 1.0 \
	normal_window_opacity 0.95 \
	window_animation_duration 0.5 \
	window_animation_easing ease_out_quint \
	insert_feedback_color 0xff9dd274 \
	split_ratio 0.50 \
	auto_balance off \
	mouse_modifier fn \
	mouse_action1 move \
	mouse_action2 resize \
	mouse_drop_action swap \
	\
	top_padding 16 \
	bottom_padding 16 \
	left_padding 16 \
	right_padding 16 \
	window_gap 16
# Exclude problematic apps from being managed:
yabai -m rule --add app="^(Family|LuLu|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Alfred|Activity Monitor|familycircled|Raycast)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
# yabai -m rule --add label="Arc" app="^Arc$" title="^(John|General|Profiles|Max|Links|Shortcuts|Icon|Advance)$" manage=off
# yabai -m rule --add label="Arc" app="Arc" title="(John|General|Profiles|Max|Links|Shortcuts|Icon|Advance)" manage=off
# yabai -m rule --add app="Arc" title="^(General|Profiles|John)$" manage=off
# yabai -m rule --add app="Arc" title="General" manage=off
# yabai -m rule --add app="Arc" title="Profiles" manage=off
yabai -m rule --add app="Arc" title="John" manage=off
yabai -m rule --add app="Arc" title="Đăng nhập - Tài khoản Google" manage=off
# yabai -m rule --add app="Arc" title="" manage=off

yabai -m rule --add app="Arc" title="General" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^Personal — Sign in – Google accounts$" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^Personal Đăng nhập — Tài khoản Google$" manage=off
# TODO: add un managed for arc setting.
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off
yabai -m signal --add event=window_focused action="~/.config/yabai/unfloat.sh"
yabai -m rule --add title="window-switcher" manage=off
yabai -m rule --add app="^Parallels Desktop" manage=off

yabai -m config layout bsp

# scratchpad setup
yabai -m rule --add app="^Music$" scratchpad=music grid=12:12:4:1:4:10
yabai -m rule --add app="^Home$" scratchpad=home grid=12:12:4:1:4:10
yabai -m rule --add app="^iPhone Mirroring$" scratchpad=iphone grid=12:12:4:1:4:10
yabai -m rule --add app="^Alacritty$" scratchpad=throwaway grid=12:12:9:1:3:8
yabai -m rule --add app="^Safari$" scratchpad=safari grid=12:12:4:1:4:10

echo "yabai configuration loaded..."
borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0 &
